title: "Prajwal Hegde"
author: "Prajwal Hegde"
description: "Made by Prajwal Hegde"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://drive.google.com/file/d/1Get6E_0Mhd_sHsMJi84th4-U3633wPVi/view?usp=sharing", title: "Resume"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:phegde494@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/phegde494"}
  - {title: Linkedin, url: "https://www.linkedin.com/in/prajwal-hegde-362068241/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
